name: Upload Widgetbook Review - Staging

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build App
        run: |
          flutter pub get
          flutter gen-l10n

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Build Widgetbook
        working-directory: widgetbook
        run: |
          flutter pub get
          dart run build_runner build -d
          flutter build web -t lib/main.dart

      - name: Upload Widgetbook
        working-directory: widgetbook
        run: |
          widgetbook_staging publish \
            --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY_STAGING }} \
            --repository $GITHUB_REPOSITORY \
            --actor $GITHUB_ACTOR \
            --base-branch $GITHUB_BASE_REF \
            --branch $GITHUB_HEAD_REF \
            --commit ${{ github.event.pull_request.head.sha }} \
            --experimental-visual-diff
          
          
          
#           widgetbook_debug publish --api-key b8375d5858cbe221386b1e94c89d10733be7dfe12c32b47bb02e1b9d32099a8f --repository widgetbook/groceries-demo --actor tim --base-branch main --branch feature-branch-3 --commit some_random_sha